---
- name: Adding docket apt keys
  apt_key:
    keyserver: hkp://pgp.mit.edu:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
- name: Copy docker source.list
  copy:
    src: "{{ role_path }}/files/docker-src.list"
    dest: /etc/apt/sources.list.d/docker.list
    owner: root
    group: root
    mode: 0644
- name: Installing docker nginx php-fpm and php-mysql
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 36000
    state: installed
  with_items:
    - docker-engine
    - nginx
    - php5-fpm
    - php5-mysql
    - mysql-client
    - python-mysqldb
    - php5-curl
    - php5-cli
