---
- name: Create new database for wordpress if not exist
  shell: mysql -u root -p{{mysql_password}} -h 127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS wordpress;'

- name: Create tables if not exist
  shell: mysql -u root -p{{mysql_password}} -h 127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS wordpress;'

- name: Create doc root directory
  file:
    path: /var/www/
    state: directory
    mode: 0755
- name: Downloading wordpress
  get_url:
    url: http://wordpress.org/latest.tar.gz
    dest: /tmp/latest.tar.gz
    mode: 600
- name: Extracting wordpress to docroot
  unarchive:
    src: /tmp/latest.tar.gz
    dest: /var/www/
    remote_src: True
- name: Setting permission on docroot
  file:
    path: /var/www/
    owner: www-data
    group: ubuntu
    mode: 0644
    recurse: yes
- name: Setting 755 perm on direcotries
  command: find /var/www/ -type d -exec chmod 0755 {} \;
