---
- name: Create new database for wordpress if not exist
  shell: mysql -u root -p{{mysql_password}} -h 127.0.0.1 -e 'CREATE DATABASE IF NOT EXISTS wordpress;'

- name: Create doc root directory
  file:
    path: /var/www/
    state: directory
    mode: 0755
- name: Downloading wordpress
  get_url:
    url: http://wordpress.org/latest.tar.gz
    dest: /tmp/latest.tar.gz
    mode: 600
- name: Extracting wordpress to docroot
  unarchive:
    src: /tmp/latest.tar.gz
    dest: /var/www/
    remote_src: True
- name: Copying wp-config.php
  copy:
    src: "{{ role_path }}/files/wp-config.php"
    dest: /var/www/wordpress/wp-config.php
    owner: www-data
    group: ubuntu
    mode: 0640
- name: Updating database password 
  shell: sed -i "s/define('DB_PASSWORD'.*/define('DB_PASSWORD','{{ mysql_password }}');/g" /var/www/wordpress/wp-config.php 

- name: Copying wordpress.sql dump 
  copy:
    src: "{{ role_path }}/files/wordpress.sql"
    dest: /tmp/wordpress.sql
    owner: root
    mode: 0400
- name: Restoring sql dump
  mysql_db:
    name: wordpress
    state: import
    target: /tmp/wordpress.sql
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ mysql_password}}"
- name: Copying user.sql dump 
  copy:
    src: "{{ role_path }}/files/users.sql"
    dest: /tmp/users.sql
    owner: root
    mode: 0400
- name: Restoring sql dump
  mysql_db:
    name: wordpress
    state: import
    target: /tmp/users.sql
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ mysql_password}}"
- name: Setting permission on docroot
  file:
    path: /var/www/
    owner: www-data
    group: ubuntu
    mode: 0644
    recurse: yes
- name: Setting 755 perm on direcotries
  command: find /var/www/ -type d -exec chmod 0755 {} \;
