---
- name: Adding mysql docker
  shell: docker ps | grep docker-mysql || docker run --name docker-mysql -t -i -p 3306:3306 -e MYSQL_ROOT_PASSWORD="{{ mysql_password }}" -d mysql/mysql-server:5.6.36
- name: Allowing connection from host
  shell: docker exec -d docker-mysql mysql --user=root --password="{{ mysql_password }}" --execute "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '"{{ mysql_password }}"' WITH GRANT OPTION; FLUSH PRIVILEGES;" 
